Document: imgmaker
Title: Debian imgmaker Manual
Author: <insert document author here>
Abstract: This manual describes what imgmaker is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/imgmaker/imgmaker.sgml.gz

Format: postscript
Files: /usr/share/doc/imgmaker/imgmaker.ps.gz

Format: text
Files: /usr/share/doc/imgmaker/imgmaker.text.gz

Format: HTML
Index: /usr/share/doc/imgmaker/html/index.html
Files: /usr/share/doc/imgmaker/html/*.html
