Document: pkpage
Title: Debian pkpage Manual
Author: <insert document author here>
Abstract: This manual describes what pkpage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pkpage/pkpage.sgml.gz

Format: postscript
Files: /usr/share/doc/pkpage/pkpage.ps.gz

Format: text
Files: /usr/share/doc/pkpage/pkpage.text.gz

Format: HTML
Index: /usr/share/doc/pkpage/html/index.html
Files: /usr/share/doc/pkpage/html/*.html
